package engine;

public enum EngineAddress {
	OVERLAND_DIR, //
	OVERLAND_X, //
	OVERLAND_Y, //
	DUNGEON_VALUE, //
	LAST_DUNGEON_X, //
	LAST_DUNGEON_Y, //
	LAST_ECL, //
	SKY_COLOR_OUTDOORS, //
	SKY_COLOR_INDOORS, //
	SAVED_TEMP_START, //
	OVERLAND_CITY, //
	FOR_LOOP_COUNT, //
	DOOR_FLAGS, //
	SEL_PC_START, //
	INDEX_OF_SEL_PC, //
	COMBAT_RESULT, //
	MOVEMENT_BLOCK, //
	SEARCH_FLAGS, //
	TRIED_TO_LEAVE_MAP, //
	PICTURE_HEAD_ID, //
	PARTY_COUNT, //
	DIVISION_MODULO, //
	TEMP_START, //
	TEXT_COLOR, //
	DUNGEON_X, //
	DUNGEON_Y, //
	DUNGEON_DIR, //
	MAP_WALL_TYPE, //
	MAP_SQUARE_INFO;
}
