package shared;

public enum GameFeature {
	BODY_HEAD, //
	EXTENDED_DUNGEON, //
	FLEXIBLE_DUNGEON_SIZE, //
	INTERACTIVE_OVERLAND, //
	OVERLAND_DUNGEON, //
	SPACE_TRAVEL, //
	SPECIAL_CHARS_NOT_FROM_FONT;
}
